
spring:
  datasource:
    url: jdbc:h2:mam/test
    username: sa
    password:
  #    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
#    username: test
#    password: 1q2w3e4r
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
