
spring:
  datasource:
    url: jdbc:mysql://34.67.24.80:3306/test?serverTimezone=Asia/Seoul
    username: test
    password: 1q2w3e4r
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
